99cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
end

99cats/app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: %w(black brown blue) }
  validates :sex, inclusion: { in: %w(M F) }

  def age
    (Date.today - self.birth_date)/365
  end

  has_many :cat_rental_requests,
    dependent: :destroy
end

99cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: %w(PENDING APPROVED DENIED)
  validate :overlapping_approved_requests?

  def overlapping_requests # will revisit
    #if start_date1 > start_date2 && end_date2 > start_date1
    rstart = self.start_date
    rend = self.end_date

    CatRentalRequest.where(
      "cat_id = #{self.cat_id} AND id != #{self.id} AND
      ((start_date BETWEEN '#{rstart}' AND '#{rend}'
      OR end_date BETWEEN '#{rstart}' AND '#{rend}')
      OR (start_date < '#{rstart}' AND end_date > '#{rend}'))"
    )
  end

  def overlapping_approved_requests?
    if overlapping_requests.where(status: "APPROVED").any?
      errors[:base] = "Overlaps approved request"
    end
  end

  def name
    self.cat.name
  end

  def approve!
    ActiveRecord::Base.transaction do
      deny!
      self.status = "APPROVED"
      self.save!
    end
  end

  def deny!
    overlapping_requests.each do |request|
      if request.status == "APPROVED"
        errors[:base] << "Already approved request"
      end
      request.status = "DENIED"
      request.save!
    end
  end

  belongs_to :cat

end

99cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

99cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @rentals = CatRentalRequest.all
    render :index
  end

  def show
    @rental = CatRentalRequest.find(params[:id])
    render :show
  end

  def new
    @rental = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @rental = CatRentalRequest.new(rental_params)
    if @rental.save
      render :show
    else
      render(
        json: @rental.errors.full_messages, status: :unprocessable_entity
      )
    end
  end

  def edit
    @rental = CatRentalRequest.find(params[:id])
    render :edit
  end

  def update
    @rental = CatRentalRequest.find(params[:id])
    if @rental.update(rental_params)
      render :show
    else
      render(
        json: @rental.errors.full_messages, status: :unprocessable_entity
      )
    end
  end

  private
  def rental_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

99cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render :show
    else
      render(
        json: @cat.errors.full_messages, status: :unprocessable_entity
      )
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      render :show
    else
      render(
        json: @cat.errors.full_messages, status: :unprocessable_entity
      )
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :description, :birth_date)
  end
end

99cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

99cats/app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

99cats/app/helpers/cats_helper.rb
module CatsHelper
end

99cats/app/views/cat_rental_requests/_form.html.erb
<% if @rental.persisted? %>
  <form action= <%= cat_rental_request_url(@rental) %> method="post">
    <input type="hidden" name="_method" value="patch">
<% else %>
  <form action="/cat_rental_requests" method="post">
<% end %>

  <input type="date" name="rental[start_date]" value= <%= @rental.start_date%>><br><br>

  <input type="date" name="rental[end_date]" value= <%= @rental.end_date%>><br><br>

  <select name="rental[cat_id]" id="cat_id"><br><br>
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.id %></option>
    <% end %>
  </select><br><br>

  <input type="submit" value="RESERVE CAT!">
</form>

99cats/app/views/cat_rental_requests/index.html.erb
<h1>Listing Rentals</h1>

<ul>
  <% @rentals.each do |rental| %>
    <li>
      <%= link_to rental.name, cat_rental_request_url(rental) %>
    </li>
  <% end %>
</ul>

99cats/app/views/cat_rental_requests/new.html.erb
<h1>File a Cat Rental!</h1>
<%= render "form" %>

99cats/app/views/cat_rental_requests/show.html.erb
<h1><%= @rental.name %></h1>

<table cellpadding="10">
  <tr>
    <% @rental.attributes.keys.drop(1).take(4).each do |key| %>
    <th> <%= key %> </th>
    <% end %>
  </tr>
  <tr>
    <% @rental.attributes.values.drop(1).take(4).each do |val| %>
    <td> <%= val %> </td>
    <% end %>
  </tr>
</table>

99cats/app/views/cats/_form.html.erb
<% if @cat.persisted? %>
  <form action= <%= cat_url(@cat) %> method="post">
    <input type="hidden" name="_method" value="patch">
<% else %>
  <form action="/cats" method="post">
<% end %>

  <input type="text" name="cat[name]" value= <%= @cat.name %> > <br><br>

  <input type="date" name="cat[birth_date]" value= <%= @cat.birth_date%>><br><br>

  <select name="cat[color]" id="cat_color"><br><br>
    <% case @cat.color %>
    <% when 'brown' %>
      <option value="brown" selected>Brown</option>
      <option value="black">Black</option>
      <option value="blue">Blue</option>
    <% when 'black'%>
      <option value="brown">Brown</option>
      <option value="black" selected>Black</option>
      <option value="blue">Blue</option>
    <% when 'blue'%>
      <option value="brown">Brown</option>
      <option value="black">Black</option>
      <option value="blue" selected>Blue</option>
    <% else %>
      <option value="brown">Brown</option>
      <option value="black">Black</option>
      <option value="blue">Blue</option>
    <% end %>
  </select><br><br>

  <% if @cat.sex == "F" %>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" checked>
    <label for="cat_sex_female">Female</label>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
    <label for="cat_sex_male">Male</label><br><br>
  <% elsif @cat.sex == "M" %>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F">
    <label for="cat_sex_female">Female</label>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" checked>
    <label for="cat_sex_male">Male</label><br><br>
  <% else %>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F">
    <label for="cat_sex_female">Female</label>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M">
    <label for="cat_sex_male">Male</label><br><br>
  <% end %>


  <label for="cat_biography">Cat's History</label><br><br>
    <textarea name="cat[description]" id="cat_biography"><%=@cat.description %></textarea><br><br>
  <input type="submit" value="CAT!">
</form>

99cats/app/views/cats/edit.html.erb
<h1>Edit an Existing Cat</h1>
<%=  render "form" %>

99cats/app/views/cats/index.html.erb
<h1>Listing Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= link_to cat.name, cat_url(cat) %>
    </li>
  <% end %>
</ul>

99cats/app/views/cats/new.html.erb
<h1>Create a new cat!</h1>

<%= render "form" %>

99cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<%= @cat.description %>
<table cellpadding="10">
  <tr>
    <% @cat.attributes.keys.drop(1).take(5).each do |key| %>
    <th> <%= key %> </th>
    <% end %>
  </tr>
  <tr>
    <% @cat.attributes.values.drop(1).take(5).each do |val| %>
    <td> <%= val %> </td>
    <% end %>
  </tr>
</table>

99cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>